server:
  port: 8088
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: ly-gateway
    
  redis:
    host: localhost
    port: 6379
    password:
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@tokenInfoKeyResolver}"
            rate-limiter: "#{@redisRateLimiter}"
            
        #- TokenVerification
            
      routes:
      # 企业接口
      - id: enterprise_route
        uri: lb://LY-SERVER
        predicates:
          - Path= /api/**
          
        filters:
          - name: DataProcess
            args:
              caller-service:
                oms: "#{@omsInputService}"
      
custom:
    replenishRate: 1
    burstCapacity: 2
    token-list:
      - channelCode: heqiauto
        accessToken: ASDFGH
        
      - channelCode: heqitest
        accessToken: QWERTY
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
                              
logging:
  level:
    org.springframework.cloud.gateway: debug
