#spring.application.name=ly-gateway
server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: ly-gateway
    
  redis:
    host: localhost
    port: 6379
    password:
    
  cloud:
    gateway:
      routes:
     
      - id: requestratelimiter_route
        uri: http://172.18.188.160:8081
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@remoteAddrKeyResolver}"
            rate-limiter: "#{@redisRateLimiter}"
            
        - TokenVerification
        
        predicates:
        - Header=token, ASDFGH

custom:
    replenishRate: 100
    burstCapacity: 200
    token-list:
      - channel: heqiauto
        token: ASDFGH 
        
      - channel: heqitest
        token: ASDFGH    
