server:
  port: 8083
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: ly-gateway
    
  redis:
    host: localhost
    port: 6379
    password:
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          
      default-filters:
        - name: RequestRateLimiter
          args:
            key-resolver: "#{@tokenInfoKeyResolver}"
            rate-limiter: "#{@redisRateLimiter}"
            
        - TokenVerification
        
        
        - name: HystrixCustom
          args:
            name: authHystrixCommand
            fallbackUri: forward:/fallback
              
      routes:
      # 企业接口
      - id: enterprise_route
        uri: http://localhost:8050
        predicates:
          - Path= /server/ent/**
          
        filters:
          #- SetResponseHeader=X-Response-Foo, ent
          
      
      # 用户接口
      - id: user_route
        uri: http://localhost:8050
        
        predicates:
          - Path= /security/user/**
          
        filters:
        
          #- SetResponseHeader=X-Response-Foo, user
          

custom:
    replenishRate: 1
    burstCapacity: 2
    token-list:
      - channelCode: heqiauto
        accessToken: ASDFGH
        
      - channelCode: heqitest
        accessToken: QWERTY
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
                              
logging:
  level:
    org.springframework.cloud.gateway: debug
